# Generated by Django 4.1.2 on 2022-11-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='linkedIn',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='varsityId',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
