# Generated by Django 4.1.2 on 2022-12-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_linkedin_alter_user_varsityid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='media')),
                ('position', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedIn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='varsityEmail',
        ),
        migrations.RemoveField(
            model_name='user',
            name='varsityId',
        ),
    ]
