# Generated by Django 4.1.2 on 2022-12-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alumnisheet_remove_user_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedIn',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='varsityEmail',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='varsityId',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
