# Generated by Django 4.1.2 on 2022-12-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_linkedin_user_password1_user_password2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnisheet',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
