# Generated by Django 4.1.2 on 2022-12-28 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
